### ISSUE TITLE
github上でbuildができない件について

### ISSUE THREAD

**Issue by shunki1006** [KBKN-Autonomous-Robotics-Lab/orange_ros2_docker#12]
buildできない, 原因調査中.

**Comment by Alpaca-zip** [comment]
以下の箇所で`chown: invalid user: 'ubuntu:ubuntu'`というエラーが出てbuildが通りません。
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2_docker/blob/f76d33247be757a487f751693ad8f626b489da47/Dockerfile#L70

この問題は、`tiryoh/ros2-desktop-vnc:humble`のDockerfileに先週追加されたコミットで、ubuntuというユーザーを明示的に作成している部分が削除されたためだと思います。
https://github.com/Tiryoh/docker-ros2-desktop-vnc/commit/feaaf44e4d2a1f35dcdd85096b49e0b9dcc5f77a

~したがって、私たちのDockerfile内で以下のようにubuntuユーザーを追加してあげれば解決しそうです。~
~`useradd -m ubuntu && echo "ubuntu:ubuntu" | chpasswd`~

**Comment by Alpaca-zip** [comment]
- 変更箇所が多かったため、この以下のPRの変更内容をベースにDockerfileを書き直しました。
https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/92
