### ISSUE TITLE
readmeの更新不足

### ISSUE THREAD

**Issue by kugurofu** [KBKN-Autonomous-Robotics-Lab/orange_ros2_docker#33]
ファイルを更新しましたがreadmeの更新をしておらず、説明と内容が変わってしまっています。
手が空き次第更新させていただきます。

**Comment by shunsugar** [comment]
READMEに少し加筆したので確認お願いします。

**Comment by kugurofu** [comment]
ありがとうございます。確認したのでisuueを閉じます。
